name: bartproject

dependencies:
  - python=3.9
  - openpyxl=3.1.2
  - pmdarima=2.0.3
  - numpy=1.19
  - pandas=1.5.3
  - matplotlib=3.6.3
  - seaborn=0.12.2
  - statsmodels=0.13
  - folium=0.14
  - ipython=8.8
  - ipykernel=6.19.2
  - decorator=5.1
