name: bartproject

dependencies:
  - python=3.10.8
  - openpyxl=3.1.2
  - pmdarima=2.0.3
  - numpy=1.23.5
  - pandas=1.5.3
  - matplotlib=3.6.3
  - seaborn=0.12.2
  - statsmodels=0.13.5
  - folium=0.14.0
  - ipython=8.8
  - ipykernel=6.19.2
  - decorator=5.1
